---
name: Build and upload package to PPA

on: workflow_dispatch

jobs:
  ppa-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install devscripts
        run: sudo apt install devscripts dh-make dh-golang golang-any -y

      - name: Import GPG Key
        run: echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --batch --passphrase "${{ secrets.GPG_PASSPHRASE }}" --import

      - name: Build and Upload packages
        run: |
          VERSION=$(yq e '.Standards-Version' debian/control)
          sed "s/sed-version/${VERSION}/" -i debian/changelog
          sed "s/sed-date/$(date -u "+%a, %d %b %Y %T")/" -i debian/changelog
          for distro in $(distro-info --supported); do
            # Skip if distro is bionic
            if [[ "${distro}" == "bionic" ]]; then
              continue
            fi
            # Set distro
            sed "s/sed-distro/${distro}/g" -i debian/changelog
            # Build debian packages
            echo "y" | sudo debuild -uc -us -S -sa \
              -k"shubhamtatvamasi@gmail.com" \
              -p"gpg --batch --passphrase "${{ secrets.GPG_PASSPHRASE }}" --pinentry-mode loopback"
            # Sign Changes
            debsign ../*.changes \
              -k"shubhamtatvamasi@gmail.com" \
              -p"gpg --batch --passphrase "${{ secrets.GPG_PASSPHRASE }}" --pinentry-mode loopback"
            # Upload packages
            dput --unchecked ppa:shubhamtatvamasi/helloworld ../*.changes
            # Cleanup
            rm -rf ../*.{dsc,tar.gz,build,buildinfo,changes,upload}
            # Revert distro
            sed "s/${distro}/sed-distro/g" -i debian/changelog
          done
